### ISSUE TITLE
error in servo-dependencies

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#286]
```
----------
          ID: servo-dependencies
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: git The following packages were already installed: freeglut3-dev, libgl1-mesa-dri, cmake, gperf, libssl-dev, xpra, xserver-xorg-input-void, xserver-xorg-video-dummy, xorg-dev, libfreetype6-dev, libgles2-mesa-dev, autoconf2.13, ccache, libosmesa6-dev, libglib2.0-dev, libbz2-dev
     Started: 19:50:02.445734
    Duration: 4996.04 ms
     Changes:   
```

https://github.com/servo/saltfs/blob/master/servo-build-dependencies/init.sls#L3 is where it comes from and https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html has useful information about how the saltfs pkg state works
