### ISSUE TITLE
servo-linux2's pip.installed target doesn't work

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#765]
This is what appears when servo-linux2 is highstated:
```
          ID: virtualenv
    Function: pip.installed
      Result: False
     Comment: An importable pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 20:40:14.528282
    Duration: 0.909 ms
     Changes:
```
This breaks any attempts to install new python packages on that machine.
